version: "3"
services:
  db:
    platform: linux/x86_64
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: rick-db:dev
    container_name: rick-db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "universe"
      MYSQL_USER: "rick"
      MYSQL_PASSWORD: "morty"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "80:8080"

